apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-podinfo
  namespace: podinfo-prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-http01
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - podinfo-prod.student-sgnl.dski23a.timebertt.dev  # ‚Üê DEINE DOMAIN
      secretName: prod-podinfo-tls
  rules:
    - host: podinfo-prod.student-sgnl.dski23a.timebertt.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prod-podinfo
                port:
                  number: 9898
